In [1]:
import torch

x = torch.ones(3, requires_grad=True) # False로 하면 Computational graph가 생기지 않음
print(x)

tensor([1., 1., 1.], requires_grad=True)


In [2]:

y = x + 2
# computational graph
# x 
#   \
#    "+" - y - 
#   /
# 2
print(y) # grad_fn = <AddBackward0>

tensor([3., 3., 3.], grad_fn=<AddBackward0>)


In [4]:

z = y * y * 2 # grad_fn = <MulBackward0>
print(z)

z = z.mean() # grad_fn = <MeanBackward0>
print(z)


z.backward() # dz/dx 
# < backward >
# x가 requires_grad=True인 경우에만 가능
# z가 scalar 값인 경우에만 가능(z.mean 안하면 오류남)
print(x.grad)

# 원리 : Vec tor Jaccovian Matrix Product (J.v) -> 선대 다시 공부하기!
# eigen vector도 공부..

tensor([18., 18., 18.], grad_fn=<MulBackward0>)
tensor(18., grad_fn=<MeanBackward0>)
tensor([4., 4., 4.])


In [5]:
z = y * y * 2 # grad_fn = <MulBackward0>
print(z)

#z = z.mean() # grad_fn = <MeanBackward0>
print(z)


z.backward() # dz/dx 
# < backward >
# x가 requires_grad=True인 경우에만 가능
# z가 scalar 값인 경우에만 가능(z.mean 안하면 오류남)
print(x.grad)

# 원리 : Vec tor Jaccovian Matrix Product (J.v) -> 선대 다시 공부하기!
# eigen vector도 공부..

tensor([18., 18., 18.], grad_fn=<MulBackward0>)
tensor([18., 18., 18.], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

In [7]:
z = y * y * 2 # grad_fn = <MulBackward0>
print(z)

#z = z.mean() # grad_fn = <MeanBackward0>
#print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) # dz/dx 
# < backward >
# x가 requires_grad=True인 경우에만 가능
# z가 scalar 값인 경우에만 가능(z.mean 안하면 오류남)
# z가 saclar가 아니면 벡터를 넣어주면 계산이 됨
print(x.grad)

# 원리 : Vec tor Jaccovian Matrix Product (J.v) -> 선대 다시 공부하기!
# eigen vector도 공부..

tensor([18., 18., 18.], grad_fn=<MulBackward0>)
tensor([ 6.4000, 28.0000,  4.0240])


# With no grad
(tracking 안하고 computational graph 안 그림)

Option 1 

In [8]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

x.requires_grad_(False)
print(x)

tensor([2.2208, 0.1338, 0.2222], requires_grad=True)
tensor([2.2208, 0.1338, 0.2222])


Option 2

In [9]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

x.detach()

tensor([-1.4791, -1.0029, -0.4177], requires_grad=True)


tensor([-1.4791, -1.0029, -0.4177])

Option 3

In [ ]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

with torch.no_grad():
    y = x + 2 
    print(y)

weights 비우기

In [10]:
weights = torch.ones(4, requires_grad=True)

# weights.grad.zero_() 하지 않으면 축적됨
for epoch in range(2):
    model_output = (weights * 3).sum()

    model_output.backward()

    print(weights.grad)

    

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [14]:
weights = torch.ones(4, requires_grad=True)

# weights.grad.zero_() 하지 않으면 축적됨
for epoch in range(2):
    model_output = (weights * 3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


optimizer

In [17]:
weights = torch.ones(1, 4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

In [18]:
weights = torch.ones(1, 4, requires_grad=True)

optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()