##  Cross Entropy

### 1) Numpy

In [1]:
import numpy as np

In [20]:
def cross_entropy(y, y_pred):
    loss = - np.sum(y *  np.log(y_pred))
    return loss # / float(y.shape[0])

In [23]:
# Y must be one hot encoded
# if class 0 : [1 0 0]
# if class 1 : [0 1 0]
# if class 2 : [0 0 1]
Y = np.array([1, 0, 0])

# y_pred has probabilities
Y_pred_good = np.array([0.7, 0.2, 0.1])
Y_pred_bad = np.array([0.1, 0.3, 0.6])
l1 = cross_entropy(Y, Y_pred_good)
l2 = cross_entropy(Y, Y_pred_bad)

print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')


Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


### 2) PyTorch

In [2]:
import torch
import torch.nn as nn

In [5]:
loss = nn.CrossEntropyLoss()

In [20]:
# Y must be class labels, not one-hot
# if class 0 : [0]
# if class 1 : [1]
# if class 2 : [2]
Y = torch.tensor([0])

# Y_pred must be logits, not after softmax # **** cross entropy 함수 = logsoftmax + nllloss ****
# |Y_pred| = (n_samples, n_classes)
Y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])

# 순서 바꿔서 쓰면 오류남
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(f'Loss1 numpy: {l1.item():.4f}')
print(f'Loss2 numpy: {l2.item():.4f}')

# argmax 안해도됨..?
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(predictions1)
print(predictions2)

Loss1 numpy: 0.4170
Loss2 numpy: 1.8406
tensor([0])
tensor([1])


- multiple samples 에 대해 해보기

In [21]:
# Y must be class labels, not one-hot
# if class 0 : [0]
# if class 1 : [1]
# if class 2 : [2]

# 3 samples
Y = torch.tensor([2, 0, 1])

# Y_pred must be logits, not after softmax 
# # **** cross entropy 함수 = logsoftmax + nllloss ****
# |Y_pred| = (n_samples, n_classes) = (3 , 3)
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])
Y_pred_bad = torch.tensor([[2.1, 1.0, 0.1], [0.1, 1.0, 2.1], [0.1, 3.0, 0.1]])

# 순서 바꿔서 쓰면 오류남
l1 = loss(Y_pred_good, Y)
l2 = loss(Y_pred_bad, Y)

print(f'Loss1 numpy: {l1.item():.4f}')
print(f'Loss2 numpy: {l2.item():.4f}')

# argmax 안해도됨..?
_, predictions1 = torch.max(Y_pred_good, 1)
_, predictions2 = torch.max(Y_pred_bad, 1)
print(predictions1)
print(predictions2)

Loss1 numpy: 0.3018
Loss2 numpy: 1.6242
tensor([2, 0, 1])
tensor([0, 2, 1])
